name: fyp24jd006

# frontend service defined in the docker-compose.override file
# as frontend is not running within a Docker container in production
services:
  backend:
    image: fyp24jd006/backend
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      postgresdb:
        condition: service_healthy

  postgresdb:
    image: postgres:16
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
