name: fyp24jd006

# frontend service defined in the docker-compose.override file
# as frontend is not running within a Docker container in production
services:
  backend:
    image: fyp24jd006/backend
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_USERNAME: travelplan
      SPRING_DATASOURCE_PASSWORD: travelplan
    depends_on:
      postgresdb:
        condition: service_healthy

  postgresdb:
    image: postgres:16
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: travelplan
      POSTGRES_PASSWORD: travelplan
      POSTGRES_DB: travelplan
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
